services:
#NGINX
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    env_file:
    - .env
#MARIADB
  mariadb:
    #image: mysql:latest
    container_name: mariadb
    build: ./mariadb
    restart: unless-stopped
#    environment:
#      - MYSQL_DATABASE=${MYSQL_DATABASE}
#      - MYSQL_USER=${MYSQL_USER}
#      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
#wordpress
  wordpress:
    depends_on:
      - mariadb
      - nginx
    container_name: wordpress
    build: ./wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    env_file:
    - .env

networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  db_data:
    name: db_data
  wp_data:
    name: wp_data
