services:
#NGINX
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    env_file:
    - .env
#MARIADB
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: unless-stopped
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
    env_file:
      - .env
#wordpress
  wordpress:
    depends_on:
      - mariadb
      - nginx
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
    env_file:
      - .env
    expose:
      - 9000

networks:
  inception_network:

volumes:
  db_data:
    name: "db_data"
    driver_opts:
      type: "none"
      o: "bind"
      device: '/home/ljacquem/data/mariadb'
  wp_data:
    name: "wp_data"
    driver_opts:
      type: "none"
      o: "bind"
      device: '/home/ljacquem/data/wordpress'
