services:
#NGINX
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
      - "8443:443"
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network
#MARIADB
  mariadb:
    container_name: mariadb
    build: ./mariadb
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_network
#wordpress
  wordpress:
    container_name: wordpress
    build: ./wordpress
    ports:
      - "8081:80"
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network

networks:
  inception_network:
    driver: bridge

volumes:
  db_data:
  wp_data:
